Avoid pcluster managing of custom Slurm partitions
aws/aws-parallelcluster-node pull request #539
Opened 2023-06-29 20:20 UTC by hanwen-pcluste

### Description of changes

Custom Slurm partitions will no longer be managed by pcluster clustermgtd.

Below is a list of behavior change, which may be not exhaustive
1. Custom partitions Old behavior: custom partitions had been being managed by clustermgtd. New behavior: custom partitions will not be managed by clustermgtd. 1.1 pcluster update-update-compute-fleet
Old behavior: the command had been changing status to all partitions. New behavior: the command will change status only to pcluster partitions. 1.2 when custom partitions are set to inactive
Old behavior: clustermgtd had been terminating nodes belonging to the partitions. New behavior: clustermgtd won't do anything.
1.3 protected mode
Old behavior: Any compute resource had been able to trigger protected mode, regardless of the partitions are pcluster/custom. When protected mode was triggered, all partitions containing the compute resource were set to inactive, regardless of the partitions are managed/custom. New behavior: Only compute resource belonging to pcluster partitions will be able to trigger protected mode. When protected mode is triggered, only pcluster partitions containing the compute resource will be set to inactive.
2. Custom nodes with name format: <queue name>-st/dy-<compute resource name>-\d Old behavior: the nodes had been managed by clustermgtd. New behavior: if the nodes are in pcluster partition, clustermgtd will manage it. Otherwise, clustermgtd will not manage it.
3. Custom nodes with other name formats Behavior is not changed. the nodes weren't and won't be managed by clustermgtd

### Tests
Wrote new integration tests https://github.com/aws/aws-parallelcluster/pull/5442 and unit tests
The following integration tests have been passed

```
{%- import 'common.jinja2' as common with context -%}
---
test-suites:
  schedulers:
    test_slurm.py::test_slurm:
      dimensions:
        - regions: [ "eu-central-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "ubuntu2004" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_pmix: # TODO: include in main test_slurm to reduce number of created clusters
      dimensions:
        - regions: [ "ap-south-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "centos7" ]
          schedulers: [ "slurm" ]
        - regions: [ "ap-northeast-1" ]
          instances: {{ common.INSTANCES_DEFAULT_ARM }}
          oss: [ "rhel8" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_scaling:
      dimensions:
        - regions: [ "use2-az2" ]  # do not move, unless instance type support is moved as well
          instances: [ {{ common.instance("instance_type_1") }} ]
          oss: [ "alinux2" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_error_handling:
      dimensions:
        - regions: [ "ca-central-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "alinux2" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_protected_mode:
      dimensions:
        - regions: [ "ca-central-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "rhel8" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_protected_mode_on_cluster_create:
      dimensions:
        - regions: [ "ap-east-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "centos7" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_memory_based_scheduling:
      dimensions:
        - regions: [ "ap-east-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "ubuntu2004" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_scontrol_reboot:
      dimensions:
        - regions: [ "us-east-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "ubuntu2004" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_scontrol_reboot_ec2_health_checks:
      dimensions:
        - regions: [ "us-east-2" ]
          instances: [ "t2.medium" ]
          oss: [ "ubuntu2004" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_overrides:
      dimensions:
        - regions: [ "me-south-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "ubuntu2004" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_scontrol_update_nodelist_sorting:
      dimensions:
        - regions: [ "ca-central-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "alinux2" ]
          schedulers: [ "slurm" ]
    test_slurm_accounting.py::test_slurm_accounting:
      dimensions:
        - regions: [ "ap-south-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "ubuntu2004" ]
          schedulers: [ "slurm" ]
    test_slurm_accounting.py::test_slurm_accounting_disabled_to_enabled_update:
      dimensions:
        - regions: [ "us-west-2" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "centos7" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_reconfigure_race_condition:
      dimensions:
        - regions: [ "af-south-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "alinux2" ]
          schedulers: [ "slurm" ]
    test_slurm.py::test_slurm_custom_partitions:
      dimensions:
        - regions: [ "us-east-1" ]
          instances: {{ common.INSTANCES_DEFAULT_X86 }}
          oss: [ "alinux2" ]
          schedulers: [ "slurm" ]
```

### References
* Link to related PRs in other packages (i.e. cookbook, node).
* Link to documentation useful to understand the changes.

### Checklist
- [ ] Make sure you are pointing to **the right branch** and add a label in the PR title (i.e. **2.x** vs **3.x**)
- [ ] Check all commits' messages are clear, describing what and why vs how.
- [ ] Make sure **to have added unit tests or integration tests** to cover the new/modified code.
- [ ] Check if documentation is impacted by this change.

Please review the [guidelines for contributing](../CONTRIBUTING.md) and [Pull Request Instructions](https://github.com/aws/aws-parallelcluster/wiki/Git-Pull-Request-Instructions).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-07-03 15:29 UTC, jdeamicis requested changes
There are several new lines that are not covered by unit tests. We must address this before merging.

2023-07-03 15:29 UTC, jdeamicis commented on src/slurm_plugin/clustermgtd.py
> +                self._partitions_protected_failure_count_map[queue_name][compute_resource] = 1
Nitpick: can't we use the `dict.setdefault()` method the same way we use it below in line 1065?

2023-07-04 11:33 UTC, jdeamicis commented on src/common/schedulers/slurm_commands.py
> +        nodes = _get_all_partition_nodes(",".join(PartitionNodelistMapping.instance().get_partitions()))
Do we still want this with the logic we chose to implement (i.e. _allowing_ users to add nodes in PC-managed partitions)?

2023-07-05 14:42 UTC, jdeamicis commented on src/common/schedulers/slurm_commands.py
> +            partition_nodelist_json = os.path.join(
I don't understand why Codecov complains about this: this should be covered by the new `test_get_partition_nodelist_mapping` defined below (see `test_slurm_commands.py`).

2023-07-05 14:42 UTC, jdeamicis commented on src/common/schedulers/slurm_commands.py
> +        return self.partition_nodelist_mapping
Same thing here (see comment above).

2023-07-05 14:48 UTC, jdeamicis commented on src/common/schedulers/slurm_commands.py
> +    show_partition_info_command = (
It makes little sense to test this if we have to mock the result of the actual Slurm command.

The `PartitionNodelistMapping.get_partitions()` part is covered by the new test class `TestPartitionNodelistMapping` tests.

Another unit test was created for the `get_partition_grep_filter` function.

The third line is a simple Python f-string.

2023-07-05 15:01 UTC, hanwen-pcluste reviewed
LGTM. Because I cannot approve my own PR. @jdeamicis , feel free to approve the PR

2023-07-05 15:01 UTC, hanwen-pcluste commented on src/common/schedulers/slurm_commands.py
> +            partition_nodelist_json = os.path.join(
~~Because we mocked it in the unit tests. I think we can leave this as is~~

2023-07-05 15:01 UTC, hanwen-pcluste commented on src/common/schedulers/slurm_commands.py
> +        return self.partition_nodelist_mapping
Same answer

2023-07-05 17:45 UTC, jdeamicis commented on src/common/schedulers/slurm_commands.py
> +            partition_nodelist_json = os.path.join(
We are not really mocking the reading of the file, we are only mocking the value of the global variable `SLURM_CONF_DIR` to be under the test data directory of pytest.

I believe Codecov is getting crazy here.

2023-07-05 17:46 UTC, jdeamicis commented on src/common/schedulers/slurm_commands.py
> +        return self.partition_nodelist_mapping
We are not really mocking the reading of the file, we are only mocking the value of the global variable `SLURM_CONF_DIR` to be under the test data directory of pytest.

I believe Codecov is getting crazy here.

2023-07-05 23:49 UTC, jdeamicis submitted a review, later dismissed

2023-07-06 14:28 UTC, jdeamicis approved these changes

2023-07-06 14:35 UTC, merged